import Cell from './Cell/Cell'
import './cells.css'
const Cells = ({width,height,arrayLength,children}:any) => {
    const array=new Array(arrayLength)
    console.log(array.length,width)
  return (
    <div className="cells ">

        {
          array.length===1?(
            (
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
            )
          ):(<></>)
        }
        {
          array.length===2?(
            (
                <>
               <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                </>
            )
          ):(<></>)
        }
        {
          array.length===3?(
            (
                <>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                </>
            )
          ):(<></>)
        }
        {
          array.length===4?(
            (
                <>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
               <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                </>
            )
          ):(<></>)
        }
        {
          array.length===5?(
            (
                <>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                </>
            )
          ):(<></>)
        }
        {
          array.length===6?(
            (
                <>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                </>
            )
          ):(<></>)
        }
        {
          array.length===7?(
            (
                <>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                </>
            )
          ):(<></>)
        }
        {
          array.length===8?(
            (
                <>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                <Cell
                width={width}
                height={height}
                >{children}</Cell>
                </>
            )
          ):(<></>)
        }
        
    </div>
  )
}

export default Cells